name: minzip
description: Compression for small strings
version: 0.0.1
homepage: https://github.com/jasonrdsouza/minzip
repository: https://github.com/jasonrdsouza/minzip

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: ^1.16.8
  pedantic: ^1.11.0
  build_runner:
  build_test:
  build_web_compilers:
